caja_banco/config/routes.rb
Rails.application.routes.draw do

  resources :asientos_automaticos_detalles

  resources :asientos_automaticos

  resources :cuentas

  get 'libros_de_cajas/libro_de_caja'

  resources :apertura_cajas_detalles

  get 'audit/index'

  resources :parametros

  get 'libros_de_bancos/libro_de_banco'

  resources :apertura_cajas

  resources :movimientos_de_cajas do
    resources :movimientos_de_cajas_detalles
  end

  resources :movimientos_de_bancos do
    resources :movimientos_de_bancos_detalles
  end

  resources :boletas_de_depositos do
    resources :boletas_de_depositos_detalles
  end

  resources :auditorias

  resources :cajas

  resources :cheques_propios

  resources :chequeras

  resources :cuentas_bancarias

  resources :firmantes

  resources :cheques_entrantes

  resources :personas

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :estados

  resources :tipos_de_personas

  resources :tipos_de_movimientos

  resources :bancos

  devise_for :users, path: "/", path_names: {
    sign_in:        'login',
    sign_out:       'logout',
    password:       'secret',
    confirmation:   'verification',
    unlock:         'unblock',
    registration:   'register',
    sign_up:        ''
  }

  resources :users

  get 'home/index'

 root 'home#index'

end

caja_banco/app/models/departamento.rb
class Departamento < ActiveRecord::Base
  audited
  belongs_to :pais
  has_many :ciudades, dependent: :restrict_with_error
  has_many :bancos, dependent: :restrict_with_error
  has_many :personas, dependent: :restrict_with_error

  validates :descripcion,
		:presence => {
			message: 'Este campo es requerido'},
		:length => {
			:maximum => 20,
			:too_long => 'debe tener como maximo %{count} caracteres'}
	validates :pais_id,
		:presence => {
			message: 'Debe seleccionar un pais'}
	def nombre
    "#{descripcion}"
  end
end

caja_banco/app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamento = Departamento.new
    @departamentos = Departamento.all

    @pais= Pais.new
    @persona = Persona.new
    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @departamentos }
        format.pdf { render_departamento_list(@departamentos) }
    end
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.new(departamento_params)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departamento }
      format.js
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)
    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamentos_url }
        format.json { render :show, status: :created, location: @departamento }
        format.js
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamentos_url }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    respond_to do |format|
      if @departamento.destroy
        format.html { redirect_to departamentos_url }
        format.json { head :no_content }
      else
        format.html { redirect_to departamentos_url, notice: 'No se puede eliminar.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:descripcion, :pais_id)
    end
    def render_departamento_list(departamento)
      report = ThinReports::Report.new layout: File.join(Rails.root, 'app','views', 'departamentos', 'show.tlf')

      departamento.each do |task|
        report.list.add_row do |row|
          row.values name: task.descripcion,
                     pais: task.pais.descripcion
          row.item(:name).style(:color, 'red')
          row.item(:pais).style(:color, 'red')
        end
      end
    report.page.item(:logo).src = File.join(Rails.root, 'public','uploads', 'parametro', 'logo_empresa', '3', 'logo.png')
    report.page.item(:elaboracion).value(current_user.username)
    report.page.item(:fecha_elaboracion).value(Time.current.to_s)
      send_data report.generate, filename: 'departamentos.pdf',
                                   type: 'application/pdf',
                                   disposition: 'attachment'
      end
end

caja_banco/app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

caja_banco/app/views/departamentos/_form.html.erb
<% remote ||= false %>
<%= form_for @departamento, remote: remote , validate: true do |f| %>
<div class="row">
  	<div class="col-md-4">
	    <div class="field">
			<%= f.label :descripcion, class: 'required' %>
			<%= f.text_field :descripcion , autofocus:true , :class => 'form-control' %>
		</div>
	</div>
	<div class="col-md-4">
	  <div class="field">
        <label for="departamento_pais_id" class="required">Pais
          <%= link_to new_pais_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :pais_id,
          options_from_collection_for_select(Pais.all, :id, :nombre, @departamento.pais_id),
          {prompt: true}, id: "departamento_pais_id", include_blank: true, class: "form-control"%>
    </div>
	</div>
</div>
</br>
<div class="col-md-offset-10">
  <div class="actions">
   <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
    <% if controller.action_name == 'new' or controller.action_name == 'index' %>
      <%= f.submit "Agregar", :class => 'btn btn-primary'%>
    <% elsif controller.action_name == 'edit' %>
      <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
    <% end %>
  </div>
</div>
<% end %>
<div id="modal_pais"></div>
<div class="separador"></div>

<script type="text/javascript">
  $(document).ready(function() {
      $('.datepicker').datetimepicker({
      locale:'es'
    });
  });
    //Cuando se abra un modal activa la las validaciones del lado del cliente
  $('#modal_pais ').on('shown.bs.modal', function () {
      $('#new_pais ').enableClientSideValidations();
  })
</script>

caja_banco/app/views/departamentos/create.js.erb
$("#modal_departamento .modal").modal("hide");
$("#ciudad_departamento_id").append("<option value='<%= @departamento.id %>'><%= @departamento.nombre %></option>");
$("#banco_departamento_id").append("<option value='<%= @departamento.id %>'><%= @departamento.nombre %></option>");
$("#persona_departamento_id").append("<option value='<%= @departamento.id %>'><%= @departamento.nombre %></option>");

caja_banco/app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

caja_banco/app/views/departamentos/edit.js.erb
$("#form-toggle").html(" <%= escape_javascript render  'form', departamento: @departamento %>");

$("html, body").scrollTop(0);
$('#form-toggle').fadeIn(500);
if($('#gbtn1').hasClass('glyphicon glyphicon-plus')){
	$('#gbtn1').removeClass('glyphicon glyphicon-plus');
	$('#gbtn1').addClass('glyphicon glyphicon-chevron-up');
}

document.getElementById("titulo_departamento").innerHTML = "Editando Departamento";

$("#btn_cancelar").click(function() {
  location.href = "/departamentos";
});

caja_banco/app/views/departamentos/index.html.erb
<h1 id="titulo_departamentos"> Departamentos <button type="button" class="btn btn-info btn-outline btn-circle" id="btn1"><span class="glyphicon glyphicon-chevron-up" id="gbtn1"></span></button></h1>
<div id="form-toggle">
  <%= render 'form' %>
</div>
<br>
<div class="reports" style="margin-left: 90.333333%">
  <%= link_to '#', onclick: "printpage()", class: 'btn btn-print btn-outline btn-circle', title: 'Imprimir reporte', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span class="glyphicon glyphicon-print" style="color: white"></span>
  <% end %>
  <%= link_to departamentos_path(@departamentos, format: 'pdf'), class: 'btn btn-pdf btn-outline btn-circle', title: 'Exportar en formato PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span style="color: white">PDF</span>
  <% end %>
  <a download="departamentos.xls" href="#" onclick="return ExcellentExport.excel(this, 'tabla_print', '');", class="btn btn-xls btn-outline btn-circle">XLS</a>
</div>
</br>
<table id="table" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Pais</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.descripcion %></td>
        <td><%= departamento.pais.descripcion %></td>
        <td>
          <%= link_to edit_departamento_path(departamento), class: 'btn btn-warning btn-outline btn-circle', title: 'Editar', 'remote' => true, 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to departamento, method: :delete, data: { confirm: 'Va eliminarlo, esta seguro?' }, class: 'btn btn-danger btn-outline btn-circle', title: 'Borrar', 'data-toggle' => 'tooltip', 'data-placement' => 'right'  do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- tabla oculta formateada para impresion -->
<div id="tabla_print">
  <h1><span><%= image_tag Parametro.last.logo_empresa_url%></span>Listado de Departamentos</h1>
  <table class="table table-striped table-hover" >
    <thead>
        <tr>
          <th>Descripcion</th>
          <th>Pais</th>
        </tr>
      </thead>
      <tbody>
        <% @departamentos.each do |departamento| %>
          <tr>
            <td><%= departamento.descripcion %></td>
            <td><%= departamento.pais.descripcion %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
  <div class="separador" style="padding-top: 650px"></div>
  <div>Elaborado por: <%=current_user.username%><span style="padding-left: 300px;">Fecha y Hora: <%= Time.current.to_s%></span></div>
</div>

caja_banco/app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

caja_banco/app/views/departamentos/new.js.erb
$("#modal_departamento").html(" <%= escape_javascript render  'departamentos/modals/departamento' %>");
$("#modal_departamento .modal-body").html(" <%= escape_javascript render  'form', departamento: @departamento, remote: true %>");
$("#modal_departamento .modal").modal("show");

caja_banco/app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @departamento.descripcion %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @departamento.pais %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>