caja_banco/config/routes.rb
Rails.application.routes.draw do

  resources :asientos_automaticos_detalles

  resources :asientos_automaticos

  resources :cuentas

  get 'libros_de_cajas/libro_de_caja'

  resources :apertura_cajas_detalles

  get 'audit/index'

  resources :parametros

  get 'libros_de_bancos/libro_de_banco'

  resources :apertura_cajas

  resources :movimientos_de_cajas do
    resources :movimientos_de_cajas_detalles
  end

  resources :movimientos_de_bancos do
    resources :movimientos_de_bancos_detalles
  end

  resources :boletas_de_depositos do
    resources :boletas_de_depositos_detalles
  end

  resources :auditorias

  resources :cajas

  resources :cheques_propios

  resources :chequeras

  resources :cuentas_bancarias

  resources :firmantes

  resources :cheques_entrantes

  resources :personas

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :estados

  resources :tipos_de_personas

  resources :tipos_de_movimientos

  resources :bancos

  devise_for :users, path: "/", path_names: {
    sign_in:        'login',
    sign_out:       'logout',
    password:       'secret',
    confirmation:   'verification',
    unlock:         'unblock',
    registration:   'register',
    sign_up:        ''
  }

  resources :users

  get 'home/index'

 root 'home#index'

end

caja_banco/app/models/banco.rb
class Banco < ActiveRecord::Base
  audited
  belongs_to :pais
  belongs_to :departamento
  belongs_to :ciudad
  has_many :movimientos_de_bancos, dependent: :restrict_with_error
  has_many :cheques_entrantes, dependent: :restrict_with_error
  has_many :boletas_de_depositos, dependent: :restrict_with_error
  has_many :cuentas_bancarias, dependent: :restrict_with_error

	validates :nombre,
		:presence => {
			message: 'Este campo es requerido'},
		:length => {
			:maximum => 20,
			:too_long => 'debe tener como maximo %{count} caracteres'}

	validates :sucursal,
		:presence => {
			message: 'Este campo es requerido'},
    :length => {
			:maximum => 20,
			:too_long => 'debe tener como maximo %{count} caracteres'}

	validates :direccion,
		:presence => {
			message: 'Este campo es requerido'},
		:length => {
			:maximum => 50,
			:too_long => 'Debe tener como maximo %{count} caracteres'}

	validates :pais_id,
		:presence => {
			message: 'Debe seleccionar un Pais'}

	validates :departamento_id,
		:presence => {
			message: 'Debe seleccionar un Departamento'}

	validates :ciudad_id,
		:presence => {
			message: 'Debe seleccionar una Ciudad'}

	validates :telefono,
		:presence => {
			message: 'Este campo es requerido'},
		:length => {
			:maximum => 20,
			:too_long => 'debe tener como maximo %{count} caracteres'},
		:format => {
			with: /\A[0-9]+\z/,
			message: 'solo permite numeros'}

	validates :correo,
		:presence =>{
				message: 'Este campo es requerido'},
		:length =>{
				:maximum => 50,
				:too_long => 'Debe tener como maximo %{count} caracteres'}

	def banco_sucursal
    "#{nombre} - #{sucursal}"
  end
end

caja_banco/app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :set_banco, only: [:show, :edit, :update, :destroy]

  # GET /bancos
  # GET /bancos.json
  def index
    @banco = Banco.new
    @bancos = Banco.all

    @pais = Pais.new
    @departamento = Departamento.new
    @ciudad = Ciudad.new
    @cuenta_bancaria = CuentaBancaria.new
    @cheque_entrante = ChequeEntrante.new

    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @bancos }
        format.pdf { render_banco_list(@bancos) }
    end
  end

  # GET /bancos/1
  # GET /bancos/1.json
  def show
    @banco = Banco.find(params[:id])
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
    respond_to do |format|
      format.js
    end
  end

  # GET /bancos/1/edit
  def edit
    @banco = Banco.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # POST /bancos
  # POST /bancos.json
  def create
    @banco = Banco.new(banco_params)

    respond_to do |format|
      if @banco.save
        format.html { redirect_to bancos_url }
        format.json { render :show, status: :created, location: @banco }
        format.js
      else
        format.html { render :new }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bancos/1
  # PATCH/PUT /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to bancos_url }
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1
  # DELETE /bancos/1.json
  def destroy
    respond_to do |format|
      if @banco.destroy
        format.html { redirect_to bancos_url }
        format.json { head :no_content }
      else
        format.html { redirect_to bancos_url, notice: 'No se puede eliminar.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banco_params
      params.require(:banco).permit(:nombre, :direccion, :telefono, :sucursal, :pais_id, :departamento_id, :ciudad_id, :correo)
    end

    def render_banco_list(banco)
      report = ThinReports::Report.new layout: File.join(Rails.root, 'app','views', 'bancos', 'show.tlf')

      banco.each do |task|
        report.list.add_row do |row|
          row.values name: task.banco_sucursal,
                     direccion: task.direccion,
                     sucursal: task.sucursal,
                     departamento: task.departamento.descripcion,
                     pais: task.pais.descripcion,
                     ciudad: task.ciudad.descripcion,
                     correo: task.correo,
                     telefono: task.telefono
          row.item(:name).style(:color, 'red')
          row.item(:direccion).style(:color, 'red')
          row.item(:sucursal).style(:color, 'red')
          row.item(:departamento).style(:color, 'red')
          row.item(:pais).style(:color, 'red')
          row.item(:ciudad).style(:color, 'red')
          row.item(:correo).style(:color, 'red')
          row.item(:telefono).style(:color, 'red')
        end
      end
    report.page.item(:logo).src = File.join(Rails.root, 'public','uploads', 'parametro', 'logo_empresa', '3', 'logo.png')
    report.page.item(:elaboracion).value(current_user.username)
    report.page.item(:fecha_elaboracion).value(Time.current.to_s)
      send_data report.generate, filename: 'bancos.pdf',
                                 type: 'application/pdf',
                                 disposition: 'attachment'
    end
end

caja_banco/app/helpers/bancos_helper.rb
module BancosHelper
end

caja_banco/app/views/bancos/_form.html.erb
<% remote ||= false %>
<%= form_for @banco, remote: remote , validate: true do |f| %>
  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="field">
        <%= f.label :nombre , class: 'required'  %>
        <%= f.text_field :nombre , autofocus:true , class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :sucursal , class: 'required' %>
        <%= f.text_field :sucursal , class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :direccion , class: 'required' %>
        <%= f.text_field :direccion , autofocus:true , :class => 'form-control' %>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="field">
        <label for="banco_pais_id" class="required">Pais
          <%= link_to new_pais_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :pais_id,
          options_from_collection_for_select(Pais.all, :id, :descripcion, @banco.pais_id),
          {prompt: true}, id: "banco_pais_id", include_blank: true, class: "form-control"%>
      </div>
      <div class="field">
        <label for="banco_departamento_id" class="required">Departamento
          <%= link_to new_departamento_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :departamento_id,
          options_from_collection_for_select(Departamento.all, :id, :descripcion, @banco.departamento_id),
          {prompt: true}, id: "banco_departamento_id", include_blank: true, class: "form-control"%>
      </div>
      <div class="field">
        <label for="banco_ciudad_id" class="required">Ciudad
          <%= link_to new_ciudad_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :ciudad_id,
          options_from_collection_for_select(Ciudad.all, :id, :descripcion, @banco.ciudad_id),
          {prompt: true}, id: "banco_ciudad_id", include_blank: true, class: "form-control"%>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="field">
        <%= f.label :telefono , class: 'required'%>
        <%= f.text_field :telefono , autofocus:true , :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :correo , class: 'required'%>
        <%= f.text_field :correo , autofocus:true , :class => 'form-control' %>
      </div>
    </div>
  </div>
</br>
  <div class="col-md-offset-10">
    <div class="actions">
     <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
      <% if controller.action_name == 'new' or controller.action_name == 'index' %>
        <%= f.submit "Agregar", :class => 'btn btn-primary'%>
      <% elsif controller.action_name == 'edit' %>
        <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
<% end %>
<div id="modal_pais"></div>
<div id="modal_departamento"></div>
<div id="modal_ciudad"></div>
<div class="separador"></div>

<script type="text/javascript">
//Cuando se abra un modal activa la las validaciones del lado del cliente
  $('#modal_pais , #modal_departamento , #modal_ciudad').on('shown.bs.modal', function () {
      $('#new_pais , #new_ciudad , #new_departamento').enableClientSideValidations();
  })
</script>

caja_banco/app/views/bancos/create.js.erb
$("#modal_banco .modal").modal("hide");
$("#cuenta_bancaria_banco_id").append("<option value='<%= @banco.id %>'><%= @banco.nombre %> - <%= @banco.sucursal %></option>");
$("#cheque_entrante_banco_id").append("<option value='<%= @banco.id %>'><%= @banco.nombre %> - <%= @banco.sucursal %></option>");

caja_banco/app/views/bancos/edit.html.erb
<h1>Editando banco</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @banco %> |
<%= link_to 'Volver', bancos_path %>

caja_banco/app/views/bancos/edit.js.erb
$("#form-toggle").html(" <%= escape_javascript render  'form', banco: @banco %>");

$("html, body").scrollTop(0);
$('#form-toggle').fadeIn(500);
if($('#gbtn1').hasClass('glyphicon glyphicon-plus')){
	$('#gbtn1').removeClass('glyphicon glyphicon-plus');
	$('#gbtn1').addClass('glyphicon glyphicon-chevron-up');
}

document.getElementById("titulo_banco").innerHTML = "Editando Banco";

$("#btn_cancelar").click(function() {
  location.href = "/bancos";
});

caja_banco/app/views/bancos/index.html.erb
<h1 id="titulo_banco"> Bancos <button type="button" class="btn btn-info btn-outline btn-circle" id="btn1"><span class="glyphicon glyphicon-chevron-up" id="gbtn1"></span></button></h1>
<div id="form-toggle">
  <%= render 'form' %>
</div>
<div class="reports" style="margin-left: 90.333333%">
  <%= link_to '#', onclick: "printpage()", class: 'btn btn-print btn-outline btn-circle', title: 'Imprimir reporte', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span class="glyphicon glyphicon-print" style="color: white"></span>
  <% end %>
  <%= link_to bancos_path(@bancos, format: 'pdf'), class: 'btn btn-pdf btn-outline btn-circle', title: 'Exportar en formato PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span style="color: white">PDF</span>
  <% end %>
  <a download="banco.xls" href="#" onclick="return ExcellentExport.excel(this, 'tabla_print', '');", class="btn btn-xls btn-outline btn-circle">XLS</a>
</div>
</br>
<table id="table" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre del Banco</th>
      <th>Sucursal</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Acciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bancos.each do |banco| %>
      <tr>
        <td><%= banco.nombre %></td>
        <td><%= banco.sucursal%></td>
        <td><%= banco.direccion %></td>
        <td><%= banco.telefono %></td>
        <td>
        <%= link_to edit_banco_path(banco), class: 'btn btn-warning btn-outline btn-circle', title: 'Editar', 'remote' => true, 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to banco, method: :delete, data: { confirm: 'Va eliminarlo, esta seguro?' }, class: 'btn btn-danger btn-outline btn-circle', title: 'Borrar', 'data-toggle' => 'tooltip', 'data-placement' => 'right'  do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- tabla oculta formateada para impresion -->
<div id="tabla_print">
  <h1><span><%= image_tag Parametro.last.logo_empresa_url%></span>Listado de Bancos</h1>
    <table class="table table-striped table-hover" >
      <thead>
        <tr>
          <th>Nombre del Banco</th>
          <th>Sucursal</th>
          <th>Direccion</th>
          <th>Telefono</th>
        </tr>
      </thead>
      <tbody>
        <% @bancos.each do |banco| %>
          <tr>
            <td><%= banco.nombre %></td>
            <td><%= banco.sucursal%></td>
            <td><%= banco.direccion %></td>
            <td><%= banco.telefono %></td>
        <% end %>
      </tbody>
    </table>
  <div class="separador" style="padding-top: 650px"></div>
  <div>Elaborado por: <%=current_user.username%><span style="padding-left: 300px;">Fecha y Hora: <%= Time.current.to_s%></span></div>
</div>

caja_banco/app/views/bancos/new.html.erb
<h1>Nuevo banco</h1>

<%= render 'form' %>

<%= link_to 'Atras', bancos_path %>

caja_banco/app/views/bancos/new.js.erb
	$("#modal_banco").html(" <%= escape_javascript render  'bancos/modals/banco' %>");
	$("#modal_banco .modal-body").html(" <%= escape_javascript render  'form', banco: @banco, remote: true %>");
	$("#modal_banco .modal").modal("show");

caja_banco/app/views/bancos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @banco.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @banco.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @banco.telefono %>
</p>

<%= link_to 'Edit', edit_banco_path(@banco) %> |
<%= link_to 'Back', bancos_path %>