caja_banco/config/routes.rb
Rails.application.routes.draw do

  resources :asientos_automaticos_detalles

  resources :asientos_automaticos

  resources :cuentas

  get 'libros_de_cajas/libro_de_caja'

  resources :apertura_cajas_detalles

  get 'audit/index'

  resources :parametros

  get 'libros_de_bancos/libro_de_banco'

  resources :apertura_cajas

  resources :movimientos_de_cajas do
    resources :movimientos_de_cajas_detalles
  end

  resources :movimientos_de_bancos do
    resources :movimientos_de_bancos_detalles
  end

  resources :boletas_de_depositos do
    resources :boletas_de_depositos_detalles
  end

  resources :auditorias

  resources :cajas

  resources :cheques_propios

  resources :chequeras

  resources :cuentas_bancarias

  resources :firmantes

  resources :cheques_entrantes

  resources :personas

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :estados

  resources :tipos_de_personas

  resources :tipos_de_movimientos

  resources :bancos

  devise_for :users, path: "/", path_names: {
    sign_in:        'login',
    sign_out:       'logout',
    password:       'secret',
    confirmation:   'verification',
    unlock:         'unblock',
    registration:   'register',
    sign_up:        ''
  }

  resources :users

  get 'home/index'

 root 'home#index'

end

caja_banco/app/controllers/movimientos_de_bancos_detalles_controller.rb
class MovimientosDeBancosDetallesController < ApplicationController
  before_action :set_movimiento_de_banco_detalle, only: [:show, :edit, :update, :destroy]

  # GET /movimientos_de_bancos_detalles
  # GET /movimientos_de_bancos_detalles.json
  def index
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimientos_de_bancos_detalles = movimiento_de_banco.movimientos_de_bancos_detalles
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movimientos_de_bancos_detalles }
    end
  end

  # GET /movimientos_de_bancos_detalles/1
  # GET /movimientos_de_bancos_detalles/1.json
  def show
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimientos_de_bancos_detalles = movimiento_de_banco.movimientos_de_bancos_detalles.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @movimientos_de_bancos_detalles }
    end
  end

  # GET /movimientos_de_bancos_detalles/new
  def new
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimiento_de_banco_detalle = movimiento_de_banco.movimientos_de_bancos_detalles.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movimiento_de_banco_detalle }
    end
  end

  # GET /movimientos_de_bancos_detalles/1/edit
  def edit
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimiento_de_banco_detalle = movimiento_de_banco.movimientos_de_bancos_detalles.find(params[:id])
  end

  # POST /movimientos_de_bancos_detalles
  # POST /movimientos_de_bancos_detalles.json
  def create
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimiento_de_banco_detalle = movimiento_de_banco.movimientos_de_bancos_detalles.create(params[:movimiento_de_banco])
    respond_to do |format|
      if @movimiento_de_banco_detalle.save
        format.html { redirect_to [@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle] }
        format.json { render :show, status: :created, location: [@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle] }
      else
        format.html { render :new }
        format.json { render json: @movimiento_de_banco_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimientos_de_bancos_detalles/1
  # PATCH/PUT /movimientos_de_bancos_detalles/1.json
  def update
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimiento_de_banco_detalle = movimiento_de_banco.movimientos_de_bancos_detalles.find(params[:id])
    respond_to do |format|
      if @movimiento_de_banco_detalle.update(movimiento_de_banco_detalle_params)
        format.html { redirect_to [@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle] }
        format.json { render :show, status: :ok, location: [@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle] }
      else
        format.html { render :edit }
        format.json { render json: @movimiento_de_banco_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimientos_de_bancos_detalles/1
  # DELETE /movimientos_de_bancos_detalles/1.json
  def destroy
    movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    @movimiento_de_banco_detalle = movimiento_de_banco.movimientos_de_bancos_detalles.find(params[:id])
    @movimiento_de_banco_detalle.destroy

    respond_to do |format|
      format.html { redirect_to @movimiento_de_banco }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimiento_de_banco_detalle
      @movimiento_de_banco_detalle = MovimientoDeBancoDetalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimiento_de_banco_detalle_params
      params.require(:movimiento_de_banco_detalle).permit(:movimiento_de_banco_id, :cuenta_bancaria_id, :descripcion, :monto)
    end
    def set_movimiento_de_banco
      @movimiento_de_banco = MovimientoDeBanco.find(params[:movimiento_de_banco_id])
    end
end

caja_banco/app/helpers/movimientos_de_bancos_detalles_helper.rb
module MovimientosDeBancosDetallesHelper
end

caja_banco/app/views/movimientos_de_bancos_detalles/_form.html.erb
<%= form_for([@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle]) do |f| %>

  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="field">
        <%= f.label :movimiento_de_banco_id %>
        <%= f.text_field :movimiento_de_banco_id, disabled: true, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :cuenta_bancaria_id %>
        <%= f.collection_select :cuenta_bancaria_id, CuentaBancaria.all, :id, :numero_cuenta, {prompt: "Seleccione una cuenta bancaria"}, {class: "form-control"} %>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="field">
        <%= f.label :descripcion %>
        <%= f.text_field :descripcion, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :monto %>
        <%= f.text_field :monto, class: 'form-control' %>
      </div>
    </div>
  </div>
  <br>
  <div class="col-md-offset-10">
    <div class="actions">
     <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
      <% if controller.action_name == 'new' or controller.action_name == 'index' %>
        <%= f.submit "Agregar", :class => 'btn btn-primary'%>
      <% elsif controller.action_name == 'edit' %>
        <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
<% end %>

caja_banco/app/views/movimientos_de_bancos_detalles/_listar.html.erb
<table>
  <thead>
    <tr>
      <th>Movimiento de banco</th>
      <th>Cuenta bancaria</th>
      <th>Descripcion</th>
      <th>Monto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movimientos_de_bancos_detalles.each do |movimiento_de_banco_detalle| %>
      <tr>
        <td><%= movimiento_de_banco_detalle.movimiento_de_banco_id %></td>
        <td><%= movimiento_de_banco_detalle.cuenta_bancaria.numero_cuenta %></td>
        <td><%= movimiento_de_banco_detalle.descripcion %></td>
        <td><%= movimiento_de_banco_detalle.monto %></td>
        <td><%= link_to 'Show', [movimiento_de_banco_detalle.movimiento_de_banco, movimiento_de_banco_detalle] %></td>
        <td><%= link_to 'Edit', edit_movimiento_de_banco_movimiento_de_banco_detalle_path(movimiento_de_banco_detalle.movimiento_de_banco, movimiento_de_banco_detalle) %></td>
        <td><%= link_to 'Destroy', [movimiento_de_banco_detalle.movimiento_de_banco, movimiento_de_banco_detalle], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

caja_banco/app/views/movimientos_de_bancos_detalles/_nuevo.html.erb
<h1>New movimiento_de_caja_detalle</h1>

<%= render 'movimientos_de_bancos_detalles/form' %>

caja_banco/app/views/movimientos_de_bancos_detalles/edit.html.erb
<h1>Editing movimiento_de_banco_detalle</h1>

<%= render 'form' %>

<%= link_to 'Show', [@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle] %> |
<%= link_to 'Back', movimiento_de_banco_movimientos_de_bancos_detalles_path %>

caja_banco/app/views/movimientos_de_bancos_detalles/index.html.erb
<h1>Listing movimientos_de_bancos_detalles</h1>

<%= render 'movimientos_de_bancos_detalles/listar'%>

<br>

<%= link_to 'New Movimiento de banco detalle', new_movimiento_de_banco_movimiento_de_banco_detalle_path %>

caja_banco/app/views/movimientos_de_bancos_detalles/new.html.erb
<h1>New movimiento_de_banco_detalle</h1>

<%= render 'form' %>

caja_banco/app/views/movimientos_de_bancos_detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movimiento de banco:</strong>
  <%= @movimiento_de_banco_detalle.movimiento_de_banco_id %>
</p>

<p>
  <strong>Cuenta bancaria:</strong>
  <%= @movimiento_de_banco_detalle.cuenta_bancaria.numero_cuenta %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @movimiento_de_banco_detalle.descripcion %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @movimiento_de_banco_detalle.monto %>
</p>

<%= link_to 'Edit', edit_movimiento_de_banco_movimiento_de_banco_detalle_path(@movimiento_de_banco_detalle.movimiento_de_banco, @movimiento_de_banco_detalle) %>