caja_banco/config/routes.rb
Rails.application.routes.draw do

  resources :asientos_automaticos_detalles

  resources :asientos_automaticos

  resources :cuentas

  get 'libros_de_cajas/libro_de_caja'

  resources :apertura_cajas_detalles

  get 'audit/index'

  resources :parametros

  get 'libros_de_bancos/libro_de_banco'

  resources :apertura_cajas

  resources :movimientos_de_cajas do
    resources :movimientos_de_cajas_detalles
  end

  resources :movimientos_de_bancos do
    resources :movimientos_de_bancos_detalles
  end

  resources :boletas_de_depositos do
    resources :boletas_de_depositos_detalles
  end

  resources :auditorias

  resources :cajas

  resources :cheques_propios

  resources :chequeras

  resources :cuentas_bancarias

  resources :firmantes

  resources :cheques_entrantes

  resources :personas

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :estados

  resources :tipos_de_personas

  resources :tipos_de_movimientos

  resources :bancos

  devise_for :users, path: "/", path_names: {
    sign_in:        'login',
    sign_out:       'logout',
    password:       'secret',
    confirmation:   'verification',
    unlock:         'unblock',
    registration:   'register',
    sign_up:        ''
  }

  resources :users

  get 'home/index'

 root 'home#index'

end

caja_banco/app/models/firmante.rb
class Firmante < ActiveRecord::Base
  audited
  belongs_to :cuenta_bancaria
  belongs_to :persona

  	validates :persona_id,
		:presence => {
			message: 'Debe seleccionar una persona'}

	validates :cuenta_bancaria_id,
		:presence => {
			message: 'Debe seleccionar una cuenta bancaria'}
end

caja_banco/app/controllers/firmantes_controller.rb
class FirmantesController < ApplicationController
  before_action :set_firmante, only: [:show, :edit, :update, :destroy]

  # GET /firmantes
  # GET /firmantes.json
  def index
    @firmantes = Firmante.all
    @firmante = Firmante.new
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @firmantes }
        format.pdf { render_firmantes_list(@firmantes) }
      end
  end

  # GET /firmantes/1
  # GET /firmantes/1.json
  def show
  end

  # GET /firmantes/new
  def new
    @firmante = Firmante.new
  end

  # GET /firmantes/1/edit
  def edit
  end

  # POST /firmantes
  # POST /firmantes.json
  def create
    @firmante = Firmante.new(firmante_params)

    respond_to do |format|
      if @firmante.save
        format.html { redirect_to firmantes_url }
        format.json { render :show, status: :created, location: @firmante }
      else
        format.html { render :new }
        format.json { render json: @firmante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firmantes/1
  # PATCH/PUT /firmantes/1.json
  def update
    respond_to do |format|
      if @firmante.update(firmante_params)
        format.html { redirect_to firmantes_url }
        format.json { render :show, status: :ok, location: @firmante }
      else
        format.html { render :edit }
        format.json { render json: @firmante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firmantes/1
  # DELETE /firmantes/1.json
  def destroy
    @firmante.destroy
    respond_to do |format|
      format.html { redirect_to firmantes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firmante
      @firmante = Firmante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firmante_params
      params.require(:firmante).permit(:cuenta_bancaria_id, :persona_id)
    end

    def render_firmantes_list(firmante)
      report = ThinReports::Report.new layout: File.join(Rails.root, 'app','views', 'firmantes', 'show.tlf')

      firmante.each do |task|
        report.list.add_row do |row|
          row.values firmante: task.persona.nombre_apellido,
                     numero_cuenta: task.cuenta_bancaria.numero_cuenta
          row.item(:firmante).style(:color, 'red')
          row.item(:numero_cuenta).style(:color, 'red')
        end
      end
    report.page.item(:logo).src = File.join(Rails.root, 'public','uploads', 'parametro', 'logo_empresa', '3', 'logo.png')
    report.page.item(:elaboracion).value(current_user.username)
    report.page.item(:fecha_elaboracion).value(Time.current.to_s)
      send_data report.generate, filename: 'firmantes.pdf',
                                 type: 'application/pdf',
                                 disposition: 'attachment'
    end
end

caja_banco/app/helpers/firmantes_helper.rb
module FirmantesHelper
end

caja_banco/app/views/firmantes/_form.html.erb
<%= form_for @firmante, validate: true do |f| %>
	<div class="row">
		<div class="col-md-4">
		  <div class="field">
        <label for="departamento_cuenta_bancaria_id" class="required">Cuenta Bancaria
          <%= link_to new_cuenta_bancaria_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :cuenta_bancaria_id,
          options_from_collection_for_select(CuentaBancaria.all, :id, :numero_cuenta, @firmante.cuenta_bancaria_id),
          {prompt: true}, id: "firmante_cuenta_bancaria_id", include_blank: true, class: "form-control"%>
    </div>
		  <div class="field">
        <label for="firmante_persona_id" class="required">Persona
          <%= link_to new_persona_path , remote: true , class: 'btn btn-info btn-outline btn-circle' do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </label>
        </br>
        <%= f.select :persona_id,
          options_from_collection_for_select(Persona.all, :id, :nombre, @firmante.persona_id),
          {prompt: true}, id: "firmante_persona_id", include_blank: true, class: "form-control"%>
    </div>
	</div>
	</div>
	</br>
  <div class="col-md-offset-10">
    <div class="actions">
     <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
      <% if controller.action_name == 'new' or controller.action_name == 'index' %>
        <%= f.submit "Agregar", :class => 'btn btn-primary'%>
      <% elsif controller.action_name == 'edit' %>
        <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
<% end %>
<div class="separador"></div>
<div id="modal_cuenta_bancaria"></div>
<div id="modal_persona"></div>

<script type="text/javascript">
   //Cuando se abra un modal activa la las validaciones del lado del cliente
  $('#modal_cuenta_bancaria , #modal_persona ').on('shown.bs.modal', function () {
      $('#new_cuenta_bancaria , #new_persona ').enableClientSideValidations();
  })
</script>

caja_banco/app/views/firmantes/edit.html.erb
<h1>Editando firmante</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @firmante %> |
<%= link_to 'Volver', firmantes_path %>

caja_banco/app/views/firmantes/edit.js.erb
$("#form-toggle").html(" <%= escape_javascript render  'form', firmante: @firmante %>");

$("html, body").scrollTop(0);
$('#form-toggle').fadeIn(500);
if($('#gbtn1').hasClass('glyphicon glyphicon-plus')){
	$('#gbtn1').removeClass('glyphicon glyphicon-plus');
	$('#gbtn1').addClass('glyphicon glyphicon-chevron-up');
}

document.getElementById("titulo_firmante").innerHTML = "Editando firmante";

$("#btn_cancelar").click(function() {
  location.href = "/firmantes";
});

caja_banco/app/views/firmantes/index.html.erb
<h1 id="titulo_firmante"> Firmantes <button type="button" class="btn btn-info btn-outline btn-circle" id="btn1"><span class="glyphicon glyphicon-chevron-up" id="gbtn1"></span></button></h1>
<div id="form-toggle">
  <%= render 'form' %>
</div>
<br>
<div class="reports" style="margin-left: 90.333333%">
  <%= link_to '#', onclick: "printpage()", class: 'btn btn-print btn-outline btn-circle', title: 'Imprimir reporte', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span class="glyphicon glyphicon-print" style="color: white"></span>
  <% end %>
  <%= link_to firmantes_path(@firmantes, format: 'pdf'), class: 'btn btn-pdf btn-outline btn-circle', title: 'Exportar en formato PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
    <span style="color: white">PDF</span>
  <% end %>
  <a download="firmantes.xls" href="#" onclick="return ExcellentExport.excel(this, 'tabla_print', '');", class="btn btn-xls btn-outline btn-circle">XLS</a>
</div>
</br>
<table id="table" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Cuenta bancaria</th>
      <th>Persona</th>
      <th>Acciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmantes.each do |firmante| %>
      <tr>
        <td><%= firmante.cuenta_bancaria.numero_cuenta %></td>
        <td><%= firmante.persona.nombre_apellido %></td>
        <td>
        <%= link_to edit_firmante_path(firmante), class: 'btn btn-warning btn-outline btn-circle', title: 'Editar', 'remote' => true, 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to firmante, method: :delete, data: { confirm: 'Va eliminarlo, esta seguro?' }, class: 'btn btn-danger btn-outline btn-circle', title: 'Borrar', 'data-toggle' => 'tooltip', 'data-placement' => 'right'  do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- tabla oculta formateada para impresion -->
<div id="tabla_print">
  <h1><span><%= image_tag Parametro.last.logo_empresa_url%></span>Listado de Firmantes</h1>
    <table class="table table-striped table-hover" >
      <thead>
    <tr>
      <th>Cuenta bancaria</th>
      <th>Persona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firmantes.each do |firmante| %>
      <tr>
        <td><%= firmante.cuenta_bancaria.numero_cuenta %></td>
        <td><%= firmante.persona.nombre_apellido %></td>
        <% end %>
      </tbody>
    </table>
<div class="separador" style="padding-top: 650px"></div>
<div>Elaborado por: <%=current_user.username%><span style="padding-left: 300px;">Fecha y Hora: <%= Time.current.to_s%></span></div>
</div>

caja_banco/app/views/firmantes/new.html.erb
<h1>Nuevo firmante</h1>

<%= render 'form' %>

<%= link_to 'Atras', firmantes_path %>

caja_banco/app/views/firmantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cuenta bancaria:</strong>
  <%= @firmante.cuenta_bancaria %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @firmante.persona %>
</p>

<%= link_to 'Edit', edit_firmante_path(@firmante) %> |
<%= link_to 'Back', firmantes_path %>